package com.example.otomoto;

public enum LekarzSpec {
    ALERGOLOGIA,
    CHIRURGIA,
    DERMATOLOGIA,
    DIABETOLOGIA,
    ENDOKRYNOLOGIA,
    GASTROENTEROLOGIA,
    GINEKOLOGIA,
    HEMATOLOGIA,
    INTERNISTA,
    KARDIOLOGIA,
    LARYNGOLOGIA,
    NEFROLOGIA,
    NEUROLOGIA,
    OKULISTYKA,
    ONKOLOGIA,
    ORTOPEDIA,
    PEDIATRA,
    PSYCHIATRIA,
    PSYCHOLOG,
    STOMATOLOGIA,
    UROLOGIA,
    WSZYSTKIE;
}
